[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Linux Embedded Journal"
authors = [{name = "mjago", email = "martyn.jago@btinternet.com"}]
dynamic = ["version", "description"]
